spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8
    username: "root"
    password: "020110"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    suffix: .html
#  mvc:
#    format:
#      date-time: yyyy-MM-dd HH:mm:ss
#    hiddenmethod:
#      filter:
#        enabled: true
